# Generated by Django 3.2.3 on 2022-07-10 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstimateChoice',
            fields=[
                ('choice', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('ticketNr', models.IntegerField(primary_key=True, serialize=False)),
                ('summary', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poker.estimatechoice')),
                ('ticketNr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poker.userstory')),
            ],
        ),
    ]
